//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configurator.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public decimal TotalPrice { get; set; }
        public System.DateTime DeliverDate { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
